### ISSUE TITLE
Map Resetting often not works.. and Stats didnt work, etc.

### ISSUE THREAD

**Issue by MrBeefchop** [Yannici/bedwars-reloaded#381]
Server: 1.8.7 Spigot

Plugin: NEWEST

Plugins on Server: There are very much.. Multiverse-Core, Worldguard, Worldedit..

Log File [No Errors]: http://pastebin.com/if9rMris

Statistics generally not works..
The TNT-Sheep didnt work too! The Sheep disappear after 11 seconds (I configurate it so).. No erros
Sometimes the map doesnt reset.. sometimes it does..

**Comment by sebastianbinder** [comment]
Because of map reset: Please check the other plugins' configurations. Try to disable all of them (except BedwarsRel and Multiverse) to debug which plugin might interfere with the reset.

Stats: your database seems to be wrong (as stated in the log file)

And in general: Try a BedwarsRel 1.2.8 build. There are many bug fixes included.

**Comment by sebastianbinder** [comment]
@MrBeefchop Is this one solved? If yes, please close the issue.

**Comment by MrBeefchop** [comment]
No I fixed the Mysql but I will test it today. Without many plugins.. c:

**Comment by sebastianbinder** [comment]
@MrBeefchop Any news?
