### ISSUE TITLE
Autostart game

### ISSUE THREAD

**Issue by helptiger** [Yannici/bedwars-reloaded#41]
A game should automatically start, when x players joined the game

**Comment by Yannici** [comment]
At the moment, the game starts when every team got min. 1 player. Isn't that okay?

**Comment by helptiger** [comment]
??? I'm not sure, should it be possible for 2 teams to battle on a 4 teams map?

**Comment by Yannici** [comment]
That's tricky, because:
When there 4 teams and 4 players in a game and 1 player don't choose a team, the game won't be started. That's bad, yes. But in another case only 2 teams are playing and the ressource spawners for the other 2 teams won't be used (performance reduction because of many items). I think I will make that configurable. It should be configurable if the game have to wait until X players joined the game OR it have to wait until all teams got min. 1 player. 

I'll change that in the next few minutes.

**Comment by Yannici** [comment]
Fixed with commit https://github.com/Yannici/bedwars-reloaded/commit/b19bc7b0797f78598c3b70d4c9c125657681eb05
