### ISSUE TITLE
Multiple Maps

### ISSUE THREAD

**Issue by Cr4fty** [Yannici/bedwars-reloaded#550]
can u add multiple maps per server for bungeecord ? the server starts and a random map boot with the plugin

**Comment by sebastianbinder** [comment]
Thank you for your feature request. We know that many users would like to see this implemented - as well as map voting. Right now, this is not on our todo list since we would have to change a lot of things in the plugin and there simply is not enough time for implementing this.
But: you can do this server-side. On restart you could swap your map directory as well as your plugins directory. So you can easily have multiple maps on one server :)

**Comment by Cr4fty** [comment]
a mapvoting pls :(
